match:
    threshold: 0.80
          
spring:
  application:
    name: data-generator
  data:
    mongodb:
      repositories:
        enabled: true
      database: datagenerator
      host: localhost
      port: 27017
  config:
    name: application,dbconfig
    location: classpath:/dbconfig/,classpath:/ 

server:
  context-path: /datagenerator
  port: 9080   
  
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
dependencycheck:
              toggle: false
              
logging:
 path: logs
 file: logs\das.log
  
file:
  types: csv, xlsx, xml, sql, json
  download:
    path: output\\
  

 
  
    
  
 
 