match:
    threshold: 0.80
          
spring:
  application:
    name: data-generator
  datasource: 
    url:    jdbc:mysql://localhost:3306/test
    username: root
    password: Epam123$$
  jpa:
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  

server:
  context-path: /poc
  port: 9080   
  
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
dependencycheck:
              toggle: false
              
logging:
 path: logs
 file: logs\das.log
  
file:
  types: csv, xlsx, xml, sql, json
  download:
    path: output
  resourcePath : src/main/resources  
    
    
parent:
  table:
      minimum:
        rowcount: 2
      percentage: 
        rowcount: 0.02
        
      
  

 
  
    
  
 
 