spring:
  application:
    name: data-generator
  data:
    mongodb:
      repositories:
        enabled: true
      database: datagenerator
      host: localhost
      port: 27017

server:
  context-path: /datagenerator
  port: 9080      